BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: entries_box
    Label:
        text: app.status_text
        size_hint_y: 0.2
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: "Create Widgets"
            on_release: app.create_widget()
        Button:
            text: "Clear Widgets"
            on_release: app.clear_all()